### ISSUE TITLE
issue with accessing root folder 

### ISSUE THREAD

**Issue by kgaonkar6** [sbg/sevenbridges-r#74]
Hello

I've been able to access the folders correctly using similar commands from your help in a previous issue. However for a particular project X. It doesn't read the root_folder and also doesn't list any folders under it just the first 100 files. We have folders and files in the same project such that the first page only has files listed in the project, will that cause an issue?

p<-a$project(name="X")
p$get_root_folder_id()
NULL

Can you please let me know how to work around this?

Thanks,
Krutika

**Comment by nanxstats** [comment]
Hi Krutika, -good question. I'm not sure if I can reproduce the issue, but I guess you might want to use `a$project(id = "username/project")` instead of `a$project(name = "project")` to retrieve the project information, because the first one would give you the essential project information including its root folder ID, and the second one will not. The example code in the [previous ticket](https://github.com/sbg/sevenbridges-r/issues/73) also used `id`.
