### ISSUE TITLE
Package 'sevenbridges' not available for R version 3.6.3

### ISSUE THREAD

**Issue by miosisoniii** [sbg/sevenbridges-r#76]
Thank you for making the master tutorial!

I am using R version 3.6.3 "Holding the Windsock" and ran into an error when loading the package "sevenbridges".

**Comment by nanxstats** [comment]
I would recommend upgrading R to the latest stable version (currently 4.0.1) and [install](https://bioconductor.org/install/) Bioconductor 3.11 since older versions of base R can only install outdated releases of Bioconductor, which come with the outdated packages.

Alternatively, try installing the development version from GitHub.
